# Generated by Django 5.0.3 on 2024-04-17 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifact', '0001_initial'),
        ('tag', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('clip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClipExportingTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
                ('task_status', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='CREATED')),
                ('exported_clip_expired_at', models.PositiveIntegerField()),
                ('path_to_export', models.TextField()),
                ('source_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clip.clip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClipTagMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clip.clip')),
                ('source_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ExportedClipMap',
            fields=[
                ('exported_clip_map_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exported_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifact.exportedartifact')),
                ('source_clip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clip.clip')),
            ],
        ),
    ]
