[tool.poetry]
name = "common-worker"
version = "0.1.0"
description = ""
authors = ["hallblazzar <hallblazzar@gmail.com>"]
readme = "README.md"
packages = [{include = "common_worker"}]

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.34.64"
requests = "^2.31.0"
urllib3 = "<2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
