[tool.poetry]
name = "whisper-api-worker"
version = "0.1.0"
description = ""
authors = ["hallblazzar <hallblazzar@gmail.com>"]
readme = "README.md"
packages = [{include = "whisper_api_worker"}]

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.11.1"
faster-whisper = "^0.10.0"
requests = "^2.31.0"
boto3 = "^1.34.36"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
