version: '3.8'
services:
  video-worker:
    image: video-worker
    build:
      context: ../../..
      dockerfile: "deployment/dockerfile/dev/Dockerfile"
    environment:
      # API server config
      - API_SERVER_URL=${API_SERVER_URL}
      # Object store config
      - CUSTOM_OBJECT_STORE_TYPE=${CUSTOM_OBJECT_STORE_TYPE}
      - CUSTOM_OBJECT_STORE_ENDPOINT=${CUSTOM_OBJECT_STORE_ENDPOINT}
      - OBJECT_STORE_BUCKET=${OBJECT_STORE_BUCKET}
      - OBJECT_STORE_BUCKET_MOUNT_ROOT=${OBJECT_STORE_BUCKET_MOUNT_ROOT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - OPENAI_KEY=${OPENAI_KEY}
    volumes:
      - ../../../video_worker:/video_worker
    devices:
      - "/dev/fuse"
    cap_add:
      - SYS_ADMIN
