# Generated by Django 5.0.3 on 2024-04-17 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionAnimationUploadingTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
                ('task_status', models.CharField(choices=[('CREATED', 'Created'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('MOVING', 'Moving'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='CREATED')),
                ('filename', models.TextField()),
                ('extension', models.CharField(max_length=32)),
                ('upload_path', models.TextField()),
                ('store_path', models.TextField()),
                ('upload_link', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WatermarkUploadingTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
                ('task_status', models.CharField(choices=[('CREATED', 'Created'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('MOVING', 'Moving'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='CREATED')),
                ('filename', models.TextField()),
                ('extension', models.CharField(max_length=32)),
                ('upload_path', models.TextField()),
                ('store_path', models.TextField()),
                ('upload_link', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransitionAnimation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('transition_animation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('source_artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artifact.artifact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('watermark_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('source_artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artifact.artifact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
