# Generated by Django 5.0.3 on 2024-04-17 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clip', '0001_initial'),
        ('footage', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEditingJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aspect_ratio', models.TextField(choices=[('Horizontal_16_9', 'Horizontal'), ('Vertical_9_16', 'Vertical'), ('Square_1_1', 'Square'), ('Social_4_5', 'Social')], default='Horizontal_16_9')),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('source_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
        migrations.CreateModel(
            name='TransitionAnimationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('source_transition_animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footage.transitionanimation')),
                ('source_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_editor.videoeditingjob')),
            ],
        ),
        migrations.CreateModel(
            name='ClipMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('source_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clip.clip')),
                ('source_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_editor.videoeditingjob')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSliceMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('source_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clip.clip')),
                ('source_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_editor.videoeditingjob')),
            ],
        ),
        migrations.CreateModel(
            name='WatermarkMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_editor.videoeditingjob')),
                ('source_watermark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footage.watermark')),
            ],
        ),
    ]
