# Generated by Django 5.0.3 on 2024-04-17 23:02

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifact', '0001_initial'),
        ('clip', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipSubtitleExportingTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
                ('task_status', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='CREATED')),
                ('source_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clip.clip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExportedClipSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifact.exportedartifact')),
                ('source_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clip.clip')),
            ],
        ),
        migrations.CreateModel(
            name='ExportedVideoSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifact.exportedartifact')),
                ('source_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('subtitle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('text', models.TextField()),
                ('source_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
        migrations.CreateModel(
            name='SubtitleGenerationTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
                ('task_status', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='CREATED')),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('prompt', models.CharField(blank=True, max_length=244, null=True)),
                ('response_format', models.CharField(blank=True, max_length=16, null=True)),
                ('temperature', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('timestamp_granularities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None)),
                ('temp_audio_file_path', models.TextField()),
                ('source_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoSubtitleExportingTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
                ('task_status', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='CREATED')),
                ('source_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
